### ISSUE TITLE
Passing additionalExpression into FilterExpressionBuilder.GetFilterExpression not working.

### ISSUE THREAD

**Issue by JaronrH** [bradwestness/collate-dot-net#8]
I needed to add my own filtering at times so I started directly accessing your FilterExpressionBuilder.GetFilterExpression() to do so.  However, I ran into an issue passing in the additionalExpression param into GetFilterExpression().  For me, the issue appeared in my EF Core 3.1 project due to trying to combine a Expression<Func<T, bool>> with an Expression using AndAlso/OrElse.

To fix it (as well as help with adding my own expressions), I added the following extensions:
```
public static class ExpressionExtensions
    {
        /// <summary>
        /// Combine Collate Entity Expressions for Filtering.
        /// </summary>
        /// <typeparam name="TEntity">Entity</typeparam>
        /// <param name="expressions">Expressions to combine.</param>
        /// <param name="filterLogic">Combination Logic.</param>
        /// <returns>Single Expression composed of expressions.</returns>
        public static Expression<Func<TEntity, bool>> CombineExpressions<TEntity>(
            this IEnumerable<Expression<Func<TEntity, bool>>> expressions, FilterLogic filterLogic = FilterLogic.And)
        {
            if (expressions == null) return x => true;
            Expression<Func<TEntity, bool>> expression = null;
            foreach (var exp in expressions)
            {
                if (expression == null)
                {
                    expression = exp;
                }
                else
                {
                    switch (filterLogic)
                    {
                        case FilterLogic.And:
                            expression = expression.AndAlso(exp);
                            break;

                        case FilterLogic.Or:
                            expression = expression.OrElse(exp);
                            break;

                        default:
                            throw new ArgumentException($"Invalid filter logic: {filterLogic}.", nameof(filterLogic));
                    }
                }
            }

            return expression ?? (x => true);
        }

        /// <summary>
        /// AndAlso for Expressions
        /// </summary>
        /// <typeparam name="T">Type</typeparam>
        /// <param name="expr1">Left Expression</param>
        /// <param name="expr2">Right Expression</param>
        /// <returns>AndAlso</returns>
        public static Expression<Func<T, bool>> AndAlso<T>(
            this Expression<Func<T, bool>> expr1,
            Expression<Func<T, bool>> expr2)
        {
            var parameter = Expression.Parameter(typeof(T));

            var leftVisitor = new ReplaceExpressionVisitor(expr1.Parameters[0], parameter);
            var left = leftVisitor.Visit(expr1.Body);

            var rightVisitor = new ReplaceExpressionVisitor(expr2.Parameters[0], parameter);
            var right = rightVisitor.Visit(expr2.Body);

            return Expression.Lambda<Func<T, bool>>(
                Expression.AndAlso(left, right), parameter);
        }

        /// <summary>
        /// AndAlso for Expressions
        /// </summary>
        /// <typeparam name="T">Type</typeparam>
        /// <param name="expr1">Left Expression</param>
        /// <param name="expr2">Right Expression</param>
        /// <returns>AndAlso</returns>
        public static Expression<Func<T, bool>> OrElse<T>(
            this Expression<Func<T, bool>> expr1,
            Expression<Func<T, bool>> expr2)
        {
            var parameter = Expression.Parameter(typeof(T));

            var leftVisitor = new ReplaceExpressionVisitor(expr1.Parameters[0], parameter);
            var left = leftVisitor.Visit(expr1.Body);

            var rightVisitor = new ReplaceExpressionVisitor(expr2.Parameters[0], parameter);
            var right = rightVisitor.Visit(expr2.Body);

            return Expression.Lambda<Func<T, bool>>(
                Expression.OrElse(left, right), parameter);
        }

        private class ReplaceExpressionVisitor
            : ExpressionVisitor
        {
            private readonly Expression _oldValue;
            private readonly Expression _newValue;

            public ReplaceExpressionVisitor(Expression oldValue, Expression newValue)
            {
                _oldValue = oldValue;
                _newValue = newValue;
            }

            public override Expression Visit(Expression node) => node == _oldValue ? _newValue : base.Visit(node);
        }
    }
```

I then simplified FilterExpressionBuilder.GetFilterExpression() to:
```
public static Expression<Func<T, bool>> GetFilterExpression<T>(FilterLogic filterLogic, IEnumerable<IFilter> filters, Expression<Func<T, bool>> additionalExpression = null)
        {
            if (filters == null || !filters.Any()) return additionalExpression ?? (x => true);
            var param = Expression.Parameter(typeof(T), "item");
            return filters
                .ToArray()
                .Where(i =>
                {
                    var property = typeof(T).GetProperty(i.Field, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static);
                    return property != null && !string.IsNullOrEmpty(i.Value);
                })
                .Select(i => Expression.Lambda<Func<T, bool>>(GetFilterExpression<T>(i.Operator, param, i.Value, i.Field), param))
                .Concat(additionalExpression == null ? new Expression<Func<T, bool>>[0] : new[] {additionalExpression})
                .CombineExpressions(filterLogic);
        }
```

No idea if this is an improvement you would like to make to your version or not but I wanted to share it just in case!  Thanks again for a great library!

**Comment by bradwestness** [comment]
These are some good refactorings and I'd like to incorporate some of them! However, it'd be nice to know that I have the issue you referenced fixed, and I'm a little unclear on how to reproduce it based on this issue. Would it be possible for you to provide a reproduction? Thanks!

**Comment by JaronrH** [comment]
Sure!

1.  Either make FilterExpressionBuilder public or share the internal methods with your Test.Core  (See https://stackoverflow.com/questions/920844/how-can-i-access-an-internal-class-from-an-external-assembly)

2)  Add the test below to Tests.Core --> FilterTests.cs


 ```
        public class TestData
        {
            /// <summary>
            /// Some Number
            /// </summary>
            public int Number { get; set; }
        }

        [TestMethod]
        public void FilterExpressionsTest()
        {
            // Create Sample Filter
            var filter = new Filter
            {
                Field = nameof(TestData.Number),
                Operator = FilterOperator.GreaterThan,
                Value = "2"
            };

            // Create Expression
            Expression<Func<TestData, bool>> expression = e => e.Number < 4;

            // Build Filter Expression
            var filterExp = FilterExpressionBuilder.GetFilterExpression<TestData>(FilterLogic.And, new[] { filter }, expression);

            // Compile Filter Expression to Function
            var filterFunc = filterExp.Compile();

            // Test!
            Assert.IsFalse(filterFunc(new TestData() { Number = 2 }));
            Assert.IsTrue(filterFunc(new TestData() { Number = 3 }));
            Assert.IsFalse(filterFunc(new TestData() { Number = 4 }));
        }
```

If you run this test, you should get the following error:

> Test method Tests.Core.FilterTests.FilterExpressionsTest threw exception: 
> System.InvalidOperationException: The binary operator AndAlso is not defined for the types 'System.Func`2[Tests.Core.FilterTests+TestData,System.Boolean]' and 'System.Boolean'.
>     at System.Linq.Expressions.Expression.AndAlso(Expression left, Expression right, MethodInfo method)
>    at System.Linq.Expressions.Expression.AndAlso(Expression left, Expression right)
>    at Collate.Internal.FilterExpressionBuilder.CombineExpressions(FilterLogic filterLogic, Expression expression1, Expression expression2) in C:\Temp\collate-dot-net-master\src\Collate\Internal\FilterExpressionBuilder.cs:line 50
>    at Collate.Internal.FilterExpressionBuilder.GetFilterExpression[T](FilterLogic filterLogic, IEnumerable`1 filters, Expression`1 additionalExpression) in C:\Temp\collate-dot-net-master\src\Collate\Internal\FilterExpressionBuilder.cs:line 31
>    at Tests.Core.FilterTests.FilterExpressionsTest() in C:\Temp\collate-dot-net-master\Tests.Core\FilterTests.cs:line 486

While you don't have this functionality exposed just now, you would hit this error if you ever did try to use it!

Let me know if you were able to reproduce the issue - thanks!

**Comment by bradwestness** [comment]
Ah, yes, I am able to reproduce the issue now. Thanks!

**Comment by bradwestness** [comment]
I added a commit and bumped the NuGet package to version 1.6, which resolves this issue. Thanks again!

**Comment by JaronrH** [comment]
Glad I could help!
